version: 2
updates:
  # JavaScript (Node.js) dependencies
  - package-ecosystem: 'npm'
    directory: '/' # Directory where package.json is located
    schedule:
      interval: 'weekly'

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/' # Root directory for GitHub Actions workflows
    schedule:
      interval: 'weekly' # Weekly is recommended for Actions updates
